version: '3'

services:
    brevets:
        build: brevets/.
        ports: 
          - "5001:5000"
        depends_on:
          - mongo
        environment:
          MONGODB_HOSTNAME: 'mongodb'
    mongo:
      image: mongo:5.0.5
    
